### ISSUE TITLE
Support macos runner

### ISSUE THREAD

**Issue by TurpIF** [ashley-taylor/junit-report-annotations-action#8]
Hello,

This is an issue I found when trying to use your GitHub Action on Android test. On GA, Android tests should run on macos runner because hardware acceleration is required to properly run the emulator.
But your action seems to not handle well the macos runner.

### How to reproduce

- Generate a simple workflow running on ubuntu
- Make it run so its green
- Change ubuntu to macos-latest

I produced a sample repository that showing this issue: https://github.com/TurpIF/junit-report-annotations-action-test/runs/836364742

### Current behavior

The workflow is failing with this stacktrace:

```
/Users/runner/work/_actions/ashley-taylor/junit-report-annotations-action/1.2/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: dlopen(/Users/runner/work/_actions/ashley-taylor/junit-report-annotations-action/1.2/node_modules/node-expat/build/Release/node_expat.node, 1): no suitable image found.  Did find:
	/Users/runner/work/_actions/ashley-taylor/junit-report-annotations-action/1.2/node_modules/node-expat/build/Release/node_expat.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/runner/work/_actions/ashley-taylor/junit-report-annotations-action/1.2/node_modules/node-expat/build/Release/node_expat.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1025:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/Users/runner/work/_actions/ashley-taylor/junit-report-annotations-action/1.2/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/runner/work/_actions/ashley-taylor/junit-report-annotations-action/1.2/node_modules/node-expat/lib/node-expat.js:4:32)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

### Expected behavior

The workflow should stay green and act like on ubuntu.

**Comment by ashley-taylor** [comment]
have made a release with your pull request
